alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias md='mkdir -p'
alias es='emacs --daemon'
alias ec='emacsclient -c'
alias eclipse='UBUNTU_MENUPROXY= eclipse'
